FROM pivotalsingapore/build-image

USER root

RUN apt-get update -qqy && \
    apt-get -qqy --no-install-recommends install \
        ca-certificates \
        xvfb && \
    apt-get clean

ENV SCREEN_WIDTH 1360
ENV SCREEN_HEIGHT 1020
ENV SCREEN_DEPTH 24
ENV DISPLAY :99.0
ENV CHROME_BIN /usr/bin/google-chrome

RUN mkdir -p /code
WORKDIR /code

ADD package.json /code/package.json

RUN curl -sL https://deb.nodesource.com/setup_5.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean

RUN npm install

ADD scripts/xvfb.sh /etc/init.d/xvfb
RUN chmod +x /etc/init.d/xvfb

COPY  . /code

RUN chmod +x /code/run-tests-in-docker.sh

CMD ./run-tests-in-docker.sh