FROM pivotalsingapore/build-image

USER ubuntu

RUN sudo apt-get update -qqy && \
    sudo apt-get -qqy --no-install-recommends install \
        ca-certificates \
        xvfb && \
    sudo apt-get clean

ENV SCREEN_WIDTH 1360
ENV SCREEN_HEIGHT 1020
ENV SCREEN_DEPTH 24
ENV DISPLAY :99.0
ENV CHROME_BIN /usr/bin/google-chrome

RUN mkdir -p /home/ubuntu/code
WORKDIR /home/ubuntu/code

ADD package.json /home/ubuntu/code/package.json

RUN ["/bin/bash", "-lc", "npm install"]

ADD scripts/xvfb.sh /etc/init.d/xvfb
RUN sudo chmod +x /etc/init.d/xvfb

COPY  . /home/ubuntu/code

RUN sudo chmod +x /home/ubuntu/run-tests-in-docker.sh

CMD ["/bin/bash", "-lc", "sh ./run-tests-in-docker.sh"]